### PR TITLE
feat: DAH-2823 Human Translations 2024-10-31

### PR DESCRIPTION
**Pull request by jimlin-sfgov**
## Description

Pull recently uploaded human translations from Phrase into the repo. Also swap in the use of one of these recent human translations keys (we were re-using another key as a stopgap while we waited for this batch of human translations).

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-2823

### Version Control

- [x] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [x] if the code changes the UI, it matches the UI design exactly

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [x] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Review by tallulahkay — APPROVED** [review]
beautiful!!

**Comment by jimlin-sfgov** [comment]
> This also covers https://sfgovdt.jira.com/browse/DAH-2820 - can it be assigned to you and added to the pr description?

@tallulahkay Good catch, I'll merge the tickets in Jira and make updates in this PR.

**Comment by jimlin-sfgov** [comment]
The code changes in this PR is in a weird state: it has updated translations for at least one other PR that has not been merged yet: https://github.com/SFDigitalServices/sf-dahlia-web/pull/2395

Waiting on that before making this ready for review

**Comment by tallulahkay** [comment]
@jimlin-sfgov you want me to manually check all of the translations keys? There has to be a better way

**Comment by jimlin-sfgov** [comment]
> you want me to manually check all of the translations keys? There has to be a better way

@tallulahkay For this PR I wrote review instructions for my own reference, as that is what I have been doing as the creator of translation PRs.

I think reviewers can just do a spot check if they can't stomach sifting through a 10+ PRs and following links to Jira tickets and Figma designs.

**Pull request merged**
