### PR TITLE
[Hotfix] Remove SRO box from 750 harrison DAH-889

### PR DESCRIPTION
**Pull request by akegan**
DAH-889

### CODE REVIEW

**Comment by software-project** [comment]
@akegan can we update credentials for the review app, please? It's failing now, so it's hard to test.

**Comment by akegan** [comment]
@software-project the creds are fixed on this one so it's ready for review

**Comment by software-project** [comment]
@akegan, another issue. This listing is not visible neither on review app nor production 🤷‍♂️

**Comment by akegan** [comment]
@software-project you can just go directly to the listing with this link https://dahlia-web-full-pr-1495.herokuapp.com/listings/a0W4U00000KKtXyUAL?preview=true. it's just not active yet

**Review by software-project — APPROVED** [review]
LGTM 👍

**Pull request merged**
