### PR TITLE
fix: DAH-3033 fix page padding in all screen sizes

### PR DESCRIPTION
**Pull request by tallulahkay**
## Description

Fix page padding for how to apply page and page header.

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-3033

### Version Control

- [ ] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [x] if the code changes the UI, it matches the UI design exactly
- [ ] if the changes include human translations, follow the [human translations process](https://sfgovdt.jira.com/l/cp/XS1KpvE4)

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [ ] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Review by chadbrokaw — APPROVED** [review]

**Comment by tallulahkay** [comment]
Yindi wants it to be aligned the whole time with the body text, if possible

**Comment by tallulahkay** [comment]
@cade-exygy @chadbrokaw I re-requested review!! I updated the styling because Yindi asked if the left spacing for the header and body could stay aligned the whole time you're resizing. 

Lmk if you can think of a more elegant way to do it! I kinda just fussed around with the css and tailwind

**Comment by cade-exygy** [comment]
https://github.com/user-attachments/assets/d95ad4ac-50f0-467a-8e85-7c0bb7c3054f

Looks really good to me! Just want to confirm that is okay that the "DAHLIA logo site header" does not need to stay aligned with the page header and body? That was something that I remember being mentioned for the previous How To Apply page (I may be mistaken, just wanted to highlight)

**Review by cade-exygy — APPROVED** [review]

**Comment by tallulahkay** [comment]
> Screen.Recording.2024-12-05.at.11.42.45.AM.mov 
> Looks really good to me! Just want to confirm that is okay that the "DAHLIA logo site header" does not need to stay aligned with the page header and body? That was something that I remember being mentioned for the previous How To Apply page (I may be mistaken, just wanted to highlight)

Ah, good point but that didn't get mentioned! I'll see what Yindi says when they review

**Pull request merged**
