### PR TITLE
fix: DAH-2843 failing test angular sign in

### PR DESCRIPTION
**Pull request by tallulahkay**
## Description

Fixes the failing angular unit test originated in [this pr](https://github.com/SFDigitalServices/sf-dahlia-web/pull/2344). 

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-2843

### Version Control

- [x] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [ ] if the code changes the UI, it matches the UI design exactly

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [ ] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Comment by cade-exygy** [comment]
Are you getting this Rails error when trying to sign in or enter invalid credentials? I am running locally
```
{
    "message": "Restforce::ResponseError, (error code missing): \nRESPONSE: \"\"",
    "status": 503
}
```

**Comment by tallulahkay** [comment]
> Are you getting this Rails error when trying to sign in or enter invalid credentials? I am running locally
> 
> ```
> {
>     "message": "Restforce::ResponseError, (error code missing): \nRESPONSE: \"\"",
>     "status": 503
> }
> ```

@cade-exygy it's not ready for review!

**Comment by tallulahkay** [comment]
> > Are you getting this Rails error when trying to sign in or enter invalid credentials? I am running locally
> > ```
> > {
> >     "message": "Restforce::ResponseError, (error code missing): \nRESPONSE: \"\"",
> >     "status": 503
> > }
> > ```
> 
> @cade-exygy it's not ready for review!

@cade-exygy it's now ready - are you getting the same error?

**Comment by cade-exygy** [comment]
> > > Are you getting this Rails error when trying to sign in or enter invalid credentials? I am running locally
> > > ```
> > > {
> > >     "message": "Restforce::ResponseError, (error code missing): \nRESPONSE: \"\"",
> > >     "status": 503
> > > }
> > > ```
> > 
> > 
> > @cade-exygy it's not ready for review!
> 
> @cade-exygy it's now ready - are you getting the same error?


Yeah. Trying to figure out if this is replicable or not.

**Review by cade-exygy — APPROVED** [review]
Testing criteria passes. Noting that API error is likely due to a data issue with my local account, but something to keep note if it pops up again.

**Comment by cade-exygy** [comment]
May be caused by other changes, but just noticing a undefined window error pop up.
Screenshot 2024-10-16 at 2 05 22 PM

**Comment by tallulahkay** [comment]
Thanks for catching @cade-exygy ! I fixed it

**Comment by cade-exygy** [comment]
> Thanks for catching @cade-exygy ! I fixed it

looks good!

**Pull request merged**
