### PR TITLE
DAH-1208 allow paragraph formatting

### PR DESCRIPTION
**Pull request by tallulahkay**
[DAH-1208](https://sfgovdt.jira.com/browse/DAH-1208)

[DAH-1208]: https://sfgovdt.jira.com/browse/DAH-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tallulahkay** [comment]
This is ready for review - I'm working on fixing the e2e tests ugh

**Comment by jimlin-sfgov** [comment]
FYI this is not a problem in prod because we do not try to sanitize Open House text on the prod branch. This is why the listing linked in the Jira ticket looks fine.

**Comment by jimlin-sfgov** [comment]
This PR is actually fixing a regression that was caused by this update: https://github.com/SFDigitalServices/sf-dahlia-web/commit/fbde74e11f639b43d2560a7abd6d0e0a5f51d683

The change in this PR is good and necessary, as we move towards only using the `renderMarkup` and `renderInlineMarkup` functions to safely render arbitrary text created in Salesforce.

The linked Jira ticket is pretty old, and is a duplicate of another [really old Jira ticket](https://sfgovdt.jira.com/browse/DAH-1153) that addresses the issue.

**Comment by jimlin-sfgov** [comment]
This e2e test is failing now because the [listing's](https://dahlia-full.herokuapp.com/listings/a0W0P00000F8YG4UAN) application window closed on December 31st. We can update the listing in salesforce to push back the application deadline another year.

```
1) Listing Details for Open Listings
     Rental Listing a0W0P00000F8YG4UAN
       displays in English:
   AssertionError: Timed out retrying after 180000ms: Expected to find content: 'Apply Online' but never did.
```

**Review by jimlin-sfgov — APPROVED** [review]
lgtm

Neither of the two failing e2e tests are related to this PR. The machine translation e2e test can be ignored. The other failing e2e test can be easily addressed by updating some data in the Salesforce Full environment.

**Comment by tallulahkay** [comment]
Updated that listing!

**Pull request merged**
