### PR TITLE
Redirect 404 to react homepage [DAH-756]

### PR DESCRIPTION
**Pull request by software-project**
Resolves react redirect issue: [DAH-756](https://sfgovdt.jira.com/browse/DAH-756)

### CODE REVIEW

**Review by james-wills-sf — CHANGES_REQUESTED** [review]
@software-project This solution doesn't work as-is, it redirects all valid (non react) urls to `/`.

For example, try going to https://dahlia-web-full-pr-1455.herokuapp.com/listings/for-rent, it redirects to the homepage.

I think the solution might be to modify the angular to redirect (via rails) to `/` if an unrecognized route is found

**Comment by james-wills-sf** [comment]
@akegan can you help QA this? the original solution didn't work so I replaced it with something I _think_ works but you're better than be at catching edge cases

**Review by james-wills-sf — APPROVED** [review]

**Comment by akegan** [comment]
not sure if this is a blocker but I just found this weirdness where if you give an invalid listing id it seems to flicker to the listing details page with no data before redirecting to the homepage?

https://user-images.githubusercontent.com/11825994/116633491-7905ed80-a90e-11eb-9b83-33833fcdeb67.mov

**Comment by james-wills-sf** [comment]
Merging this as it doesn't cause the bug above and we created a separate ticket to fix it: DAH-786

**Pull request merged**
