### PR TITLE
DAH-1101 Prevent users with South SF addresses from getting NRHP preference

### PR DESCRIPTION
**Pull request by christine-sfg**
DAH-1101

-Explicitly check for household members to have city 'San Francisco' to avoid false positives for NRHP preference
-Misc housekeeping/docs

### CODE REVIEW

**Comment by emilyjablonski** [comment]
@christine-sfg I'm a little confused by the bug, the PR description says it needs to check household members and the ticket says it needs to check the applicant?

**Comment by christine-sfg** [comment]
@emilyjablonski good question. From what i saw, the [household members list](https://github.com/SFDigitalServices/sf-dahlia-web/blob/55e359aeb3a3c9e3700a735d13df4cdf082d132c/app/assets/javascripts/short-form/ShortFormApplicationService.js.coffee#L522) also includes the applicant. I think we want to check all addresses included in the application. I will update the jira to make this clearer.

**Comment by emilyjablonski** [comment]
@christine-sfg Is it true that an applicant who has an SF address and also has household members without them can get the preference?

**Comment by christine-sfg** [comment]
@emilyjablonski Yes. From testing on full, the opposite is true as well. As long as at least one member of the household has a qualifying address, then the application should be prompted for NRHP preference.

**Review by jacksongonzales — APPROVED** [review]
Looks good after testing scenarios you and emily described above + the expected preference behavior 🎉

**Pull request merged**
