### PR TITLE
Show AMI range instead of AMI tier label DAH-560

### PR DESCRIPTION
**Pull request by akegan**
DAH-560

### CODE REVIEW

**Comment by james-wills-sf** [comment]
@akegan doing qa testing, does the table on this page fail to load for you? https://dahlia-web-full-pr-1426.herokuapp.com/tl/listings/a0W1F000002DHG3UAO

I'm getting this in the console, and didn't get it on other listings
```
Error: undefined is not an object (evaluating 'new n.google.translate')
https://dahlia-web-full-pr-1426.herokuapp.com/assets/application-e6aa0ad01a1db425f3e79d5c49861f85118de0caf0b510540ea806c31b34fa8b.js:32:20879
https://dahlia-web-full-pr-1426.herokuapp.com/assets/application-e6aa0ad01a1db425f3e79d5c49861f85118de0caf0b510540ea806c31b34fa8b.js:32:20781
https://dahlia-web-full-pr-1426.herokuapp.com/assets/application-e6aa0ad01a1db425f3e79d5c49861f85118de0caf0b510540ea806c31b34fa8b.js:5:28654
a@https://dahlia-web-full-pr-1426.herokuapp.com/assets/application-e6aa0ad01a1db425f3e79d5c49861f85118de0caf0b510540ea806c31b34fa8b.js:3:31948
https://dahlia-web-full-pr-1426.herokuapp.com/assets/application-e6aa0ad01a1db425f3e79d5c49861f85118de0caf0b510540ea806c31b34fa8b.js:4:642
r@https://dahlia-web-full-pr-1426.herokuapp.com/assets/application-e6aa0ad01a1db425f3e79d5c49861f85118de0caf0b510540ea806c31b34fa8b.js:21:13353 – undefined
```

**Review by james-wills-sf — APPROVED** [review]
@akegan code and QA lgtm except for the one issue I brought up, I'm thinking it's because of some issue with the new translation strings not having non-english translations yet?

e2e tests are failing but they seem unrelated, could be flaky or some tet needs to be updated for the new year.

lastly, did you upload these new strings to phrase?

**Comment by akegan** [comment]
Haven't uploaded strings to phrase yet. Will do it now.

Re: the error, google translate is definitely very flaky. not an officially supported tool anymore even.

**Comment by akegan** [comment]
alright I've pushed the strings to phrase + in the process ran grunt translations which found some other now-unused keys.

**Pull request merged**
