### PR TITLE
DAH-1947 prevent duplicate db entries

### PR DESCRIPTION
**Pull request by tallulahkay**
DAH-1947

The ticket says to delete stale db records. I updated the code so that, moving forward, we query the listing images by listing id and raw image url, and update the image urls if they have changed. This way, we can have minimal db entries (hopefully just 1 per image per listing) and they will stay up to date. 

I also removed the populating of image url for the whole listing because we don't really use it anymore. (We now use displayImageUrl).

### CODE REVIEW

**Review by alulabeshue-sfgov — CHANGES_REQUESTED** [review]
issue: It looks like the imageUrl in used in the [angular](https://github.com/SFDigitalServices/sf-dahlia-web/blob/main/app/assets/javascripts/short-form/templates/g1-confirmation.html.slim#L8) application during /confirmation

Screenshot 2024-02-13 at 4 12 31 PM

**Comment by tallulahkay** [comment]
@alulabeshue-sfgov I removed the image url stuff because it wasn't required for the ticket - was just trying to do some related cleanup but I can make another ticket to remove the use of image url

**Review by cade-exygy — APPROVED** [review]
Changes look good! Going to manually run the jobs on the PR env now

**Comment by cade-exygy** [comment]
Testing on the PR env: It looks like some images are being picked up and cached correctly, but I noticed that the images for this listing are not getting cached: https://dahlia-webapp-pr-2082.herokuapp.com/listings/a0W8H0000014LS9UAM

**Comment by tallulahkay** [comment]
> Testing on the PR env: It looks like some images are being picked up and cached correctly, but I noticed that the images for this listing are not getting cached: https://dahlia-webapp-pr-2082.herokuapp.com/listings/a0W8H0000014LS9UAM

@cade-exygy I think the rails cache is never being updated really because it wasn't initialized. We rely on the prefetch daily call to initialize the cache - this was my mistake I should have prepared the environment properly before anyone looked at it

**Comment by tallulahkay** [comment]
@cade-exygy which is what I was trying to solve here: https://github.com/SFDigitalServices/sf-dahlia-web/pull/2069... it's not really a problem in full and prod because of prefetch_daily (only noticeable after release and before prefetch_daily job is run)

**Comment by cade-exygy** [comment]
Looks like this is caching images correctly!

**Pull request merged**
