### PR TITLE
Optimize circleci builds #172869530

### PR DESCRIPTION
**Pull request by akegan**
@software-project creating this PR so I can look at the diff and make comments

### CODE REVIEW

**Comment by akegan** [comment]
@james-wills-sf would you be up for helping with merge conflicts on this PR too?

**Comment by james-wills-sf** [comment]
Rebased, fixed merge conflicts, and tested regular dev and release branch workflows and both pass on circleci.

**Comment by akegan** [comment]
This looks good to me. there's something funky about it waiting for e2e-sign-in-apply but I think that's just because those are expected jobs on master. I created the PR so can't approve it. @james-wills-sf can you approve if you think it's good to go?

**Comment by james-wills-sf** [comment]
@akegan I think those were just github settings.

I updated them to not require any e2e tests, then after we merge this I'll update them again to require the `e2e` job to pass

**Comment by james-wills-sf** [comment]
I'll test with e2e-production tests one more time. If those pass I'll approve and merge

**Pull request merged**
