### PR TITLE
feat: DAH-2733 checking if fcfs is sales listing

### PR DESCRIPTION
**Pull request by alulabeshue-sfgov**
## Description

FCFS changes should only apply to sales listings

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-2733

### Version Control

- [ ] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [ ] if the code changes the UI, it matches the UI design exactly

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [ ] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Comment by cade-exygy** [comment]
Code looks good, could you point me towards the review instructions?

**Comment by tallulahkay** [comment]
@alulabeshue-sfgov The listing details status on the rental fcfs listing does not match the lottery design in the figma linked in the review instructions. The design for listing statuses for lottery listings was also updated. With the current implementation, the rental listing details status shows the old design. Is that what we want?

**Comment by alulabeshue-sfgov** [comment]
> The listing details status on the rental fcfs listing does not match the lottery design in the figma linked in the review instructions. The design for listing statuses for lottery listings was also updated. With the current implementation, the rental listing details status shows the old design. Is that what we want?

Thanks @tallulahkay for catching this! I've made a change to address the issue

**Review by tallulahkay — APPROVED** [review]
Looks good!

**Pull request merged**
