### PR TITLE
Switch referral on review optional to dropdown #173721318

### PR DESCRIPTION
**Pull request by akegan**
[ticket](https://www.pivotaltracker.com/story/show/173721318)

Review instructions are in the ticket

### CODE REVIEW

**Comment by james-wills-sf** [comment]
Tested this and was able to see the salesforce values get updated, even when the demographic info was saved in the old version.


### Bug found: irrelevant to this change
While testing this, on my 3rd application for this account (last two apps were made on made, this one made on this branch) for the automated senior listing I got stuck on the this step:
- 2020-07-10 at 12 09 41 PM

With the console error:
```
Error: Service is not defined
ShortFormApplicationController/$scope.checkAfterNamePage@http://localhost:3000/assets/short-form/ShortFormApplicationController.self-488ec8871ece6df1655bce31a3e2e0a2893531e90bcf31cf1e30fda8c2b1ed6f.js?body=1:889:9
ShortFormApplicationController/$scope.handleFormSuccess/<@http://localhost:3000/assets/short-form/ShortFormApplicationController.self-488ec8871ece6df1655bce31a3e2e0a2893531e90bcf31cf1e30fda8c2b1ed6f.js?body=1:110:47
ShortFormApplicationController/$scope.handleFormSuccess@http://localhost:3000/assets/short-form/ShortFormApplicationController.self-488ec8871ece6df1655bce31a3e2e0a2893531e90bcf31cf1e30fda8c2b1ed6f.js?body=1:108:33
ShortFormApplicationController/$scope.submitForm@http://localhost:3000/assets/short-form/ShortFormApplicationController.self-488ec8871ece6df1655bce31a3e2e0a2893531e90bcf31cf1e30fda8c2b1ed6f.js?body=1:84:23
fn@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1 line 15127 > Function:4:221
expensiveCheckFn@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:16214:18
callback@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:26593:19
$eval@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:17995:28
$apply@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:18095:25
ngEventHandler/<@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:26598:23
defaultHandlerWrapper@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:3547:11
eventHandler@http://localhost:3000/assets/angular/angular.self-a4ec94b978004b45127819f4f8dda67f742334b1e952c2dc446a327714b45fb5.js?body=1:3535:23
wrapped@http://localhost:3000/assets/raven-js/dist/raven.self-dc71434ade2a333f347a557e84d3e0b57bab7bed8c6df6fc396874d15ec0c41c.js?body=1:413:21
 undefined raven.self-dc71434ade2a333f347a557e84d3e0b57bab7bed8c6df6fc396874d15ec0c41c.js:56:32

```

Note that this also happens on main, not saying it's a bug with this PR but wanted to document it somewhere.

**Comment by akegan** [comment]
@james-wills-sf I'm not sure if I've seen that one before. Would you be up for making a bug ticket for it? Maybe you could dig through sentry to see if you see folks getting a similar error on prod?

**Comment by james-wills-sf** [comment]
@akegan I'm not seeing any of these errors on sentry and I can't reproduce. I guess it's fine to ignore for now unless we start seeing it again.

**Comment by akegan** [comment]
ok strange. thanks for checking!

**Pull request merged**
