### PR TITLE
feat: DAH-2754 Add RTR Hunters View pref to application

### PR DESCRIPTION
**Pull request by jimlin-sfgov**
## Description

Show right-to-return preference question in the application, when a listing as the "Right to Return - Hunters View" preference.

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-2754

### Version Control

- [x] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [x] if the code changes the UI, it matches the UI design exactly

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [x] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Comment by tallulahkay** [comment]
2 things that may warrant other tickets: 
1. Is there a way to link to the other languages via the node in angular? it seems like the Find out more about this preference link only links to english 
2. this list is now inconsistent with the document checklist updates: https://sfgovdt.jira.com/browse/DAH-2732
Screenshot 2024-09-25 at 2 40 02 PM

**Comment by jimlin-sfgov** [comment]
@tallulahkay 

> Is there a way to link to the other languages via the node in angular?

The Angular pages are not able to automatically update the language for `readMoreUrl` links, there is not an equivalent to the `mapPreferenceLink` function in Angular.

> This list is now inconsistent with the document checklist updates

Can you be more specific? The only difference that needs to be consolidated is the name of 'SF City ID` option, but I don't want to be missing anything else.

**Comment by tallulahkay** [comment]
> Can you be more specific? The only difference I see that needs to be consolidated is the name of 'SF City ID' option, but I don't want to be missing anything else.

Yep - just the SF City ID!

**Comment by jimlin-sfgov** [comment]
@tallulahkay 

> Is there a way to link to the other languages via the node in angular?

Regarding this point again, it's not as easy as I'd hoped to replicate the React behavior in Angular. I personally think it's fine to leave as is, since the page viewer should be able to easily change the language. We can create another ticket as needed.
Screenshot 2024-09-25 at 3 16 24 PM

**Review by tallulahkay — APPROVED** [review]
Yay!

**Comment by jimlin-sfgov** [comment]
> This list is now inconsistent with the document checklist updates

Per discussion elsewhere, this will be addressed later.

**Comment by jimlin-sfgov** [comment]
Bypassing protections to merge, since e2e-legacy test failures are a known issue.

**Pull request merged**
