### PR TITLE
Update to latest pattern lib, change form-note use DAH-136

### PR DESCRIPTION
**Pull request by akegan**
This PR:
1. Updates to the latest pattern lib, including changes to form-note styling from https://github.com/SFDigitalServices/sf-dahlia-pattern-library/pull/142
1. Removes use of form-note from the cancel button on the "forgot password" page
1. Removes the use of form-note from the first page of the application and text at the beginning of some of the application pages

Before (with updated form-note styling):
Screen Shot 2020-08-31 at 2 59 43 PM
Screen Shot 2020-08-31 at 2 59 06 PM

After/current:
Screen Shot 2020-08-31 at 2 59 25 PM
Screen Shot 2020-08-31 at 2 58 44 PM
image

### CODE REVIEW

**Comment by akegan** [comment]
@cpalmatier check out this PR  + review app for the form-note changes on webapp

**Comment by akegan** [comment]
@cpalmatier pinging again on this PR to make sure that the form note changes I made on webapp match your expectations. Review app (linked with the 🚀  above) is https://dahlia-web-full-pr-1409.herokuapp.com/.

**Comment by james-wills-sf** [comment]
@akegan It feels like the old design was a little better? Maybe just applying the font size/weight instead of adding the form-note class would get it closer?

**Comment by akegan** [comment]
@james-wills-sf Chris had suggested that we switch to base paragraph for these form-note cases. I think we probably have to wait for him to weigh in

**Comment by cpalmatier** [comment]
@akegan Looks good for the most part. You could also remove the .inset class on line 11 of a4-overview.html.slim (to match it with the left/right padding on the other pages in the flow), but it's not a showstopper.

**Comment by akegan** [comment]
ok @cpalmatier I've made that update
image
@james-wills-sf this is ready for eng review now.

**Comment by james-wills-sf** [comment]
@akegan lgtm!

**Review by james-wills-sf — APPROVED** [review]

**Pull request merged**
