### PR TITLE
DAH-1616: Fix Open House Links

### PR DESCRIPTION
**Pull request by cliu02**
[DAH-1616](https://sfgovdt.jira.com/browse/DAH-1616)

[DAH-1616]: https://sfgovdt.jira.com/browse/DAH-1616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by alulabeshue-sfgov — COMMENTED** [review]
Changes look good in PR env but there is a failing react unit test.

**Review by chadbrokaw-exygy — APPROVED** [review]
Once the tests are fixed this is good to go!

**Comment by jimlin-sfgov** [comment]
> This snapshot should not be affected because this PR does not directly modify ListingDetailsPricingTable

I ran `yarn test -u` on my local copy of this PR, and 4 snapshots got updated:
Screenshot 2023-09-01 at 2 25 15 PM

I think those 4 snapshots required updating because those 4 components use `getEventNote` to render elements.

**Comment by jimlin-sfgov** [comment]
@cliu02 This looks like the culprit: https://github.com/bloom-housing/ui-components/pull/117

We need to keep our local Bloom package up to date by running `yarn` every now and then.

**Pull request merged**
