### PR TITLE
fix: DAH-2512 Remove use of deprecated lottery field in Angular condition logic

### PR DESCRIPTION
**Pull request by jimlin-sfgov**
https://sfgovdt.jira.com/browse/DAH-2512

### CODE REVIEW

**Comment by chadbrokaw** [comment]
@jimlin-sfgov Should this change also be made in the React pages?

**Comment by jimlin-sfgov** [comment]
> @jimlin-sfgov Should this change also be made in the React pages?

@chadbrokaw The React pages already handle the Salesforce API deprecation properly. There is some code cleanup needed in React, but there is another ticket to address that.

**Comment by alulabeshue-sfgov** [comment]
@jimlin-sfgov I tried following the review instructions in the jira ticket and ran an issue, I left a comment on the ticket.

@chadbrokaw For the react pages I see the [ApplicationItem](https://github.com/SFDigitalServices/sf-dahlia-web/blob/main/app/javascript/components/ApplicationItem.tsx#L44) component is using the new salesforce fields.

**Review by alulabeshue-sfgov — APPROVED** [review]
> I tried following the review instructions in the jira ticket and ran an issue, I left a comment on the ticket.

After messaging with @jimlin-sfgov the review instructions make sense. LGTM!

**Pull request merged**
