### PR TITLE
CircleCI project setup #170582273

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/170582273

### CODE REVIEW

**Comment by akegan** [comment]
The issue is that bundle install hangs while trying to install nokogiri. If you try to install using `gem install nokogiri` you get a bit more detail:
```
circleci@7b3ec891f299:~/web$ gem install nokogiri
Fetching mini_portile2-2.4.0.gem
Fetching nokogiri-1.10.9.gem
Successfully installed mini_portile2-2.4.0
Building native extensions. This could take a while...
```


Here's what I did to try to debug the issue:
- ssh'd into the build and set gemfile to version 1.10.8 instead of 1.10.9 in case that was causing the issue
- Tried following [these steps](https://nokogiri.org/tutorials/installing_nokogiri.html#ubuntu-debian) to install the right packages in the server. This is what I get from that:
```
circleci@7b3ec891f299:~/web$ sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
patch is already the newest version (2.7.5-1+deb9u1).
liblzma-dev is already the newest version (5.2.2-1.2+b1).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-5).
The following additional packages will be installed:
  dpkg-dev fakeroot fonts-lato libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libfakeroot libruby2.3 rake ruby ruby-did-you-mean ruby-minitest ruby-net-telnet
  ruby-power-assert ruby-test-unit ruby2.3 ruby2.3-dev rubygems-integration
Suggested packages:
  debian-keyring ri bundler
The following NEW packages will be installed:
  build-essential dpkg-dev fakeroot fonts-lato libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libfakeroot libruby2.3 rake ruby ruby-dev ruby-did-you-mean
  ruby-minitest ruby-net-telnet ruby-power-assert ruby-test-unit ruby2.3 ruby2.3-dev rubygems-integration
0 upgraded, 20 newly installed, 0 to remove and 2 not upgraded.
Need to get 4479 kB/9197 kB of archives.
After this operation, 34.6 MB of additional disk space will be used.
Err:1 http://security.debian.org/debian-security stretch/updates/main amd64 libruby2.3 amd64 2.3.3-1+deb9u4
  404  Not Found
Err:2 http://security.debian.org/debian-security stretch/updates/main amd64 ruby2.3 amd64 2.3.3-1+deb9u4
  404  Not Found
Err:3 http://security.debian.org/debian-security stretch/updates/main amd64 ruby2.3-dev amd64 2.3.3-1+deb9u4
  404  Not Found
Unable to correct missing packages.
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/ruby2.3/libruby2.3_2.3.3-1+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/ruby2.3/ruby2.3_2.3.3-1+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/ruby2.3/ruby2.3-dev_2.3.3-1+deb9u4_amd64.deb  404  Not Found
E: Aborting install.
```

**Comment by software-project** [comment]
@akegan I've tried that approach as well without any luck. I found a docker approach as well, but with same results.

**Comment by akegan** [comment]
Changes in https://github.com/SFDigitalServices/sf-dahlia-web/pull/1344/commits/cc36103cbaf5e082f34d6f26d7a74849433ec781 from [these steps](https://nokogiri.org/tutorials/installing_nokogiri.html#install-with-system-libraries) seem to have worked to get it to build 🤞 that the rest will work.

**Comment by akegan** [comment]
OK @software-project I updated some env vars to get rspec tests working too. I’ll leave the rest to you on Monday. FYI I noticed some of the env vars you added had the single quotes around them which caused some issues. I could tell because of the ' in the bit at the end that circleCI shows you. I replaced most of them but if you run into other issues keep an eye out for env vars they might still have the single quotes around them.

**Comment by james-wills-sf** [comment]
@akegan martin did an awesome job and got the tests passing. I think this PR is ready for review.

The ticket says we want tests running in circleci instead of semaphore, to do that I'd like to do the following:
1. tell github to mark semaphore as optional
1. merge this PR
1. mark circle ci tests as required
1. remove semaphore code

Do you know what order I should do those in? That affects whether this PR is actually done or not.

**Comment by akegan** [comment]
@james-wills-sf there isn't any semaphore code checked in as far as I know. All the config is in semaphore itself. There is some code about changing credentials in the refresh script, but it's probably worth waiting to update that until we are recovering from a refresh again. 

otherwise since both of you worked on this I think if you both sign off on the changes it should be all good. If you want a 3rd set of eyes I can take a look though.

**Comment by james-wills-sf** [comment]
@software-project can you take a look at the reorganization I did here? If it looks good to you we can merge.

Also do you know how to update the github checks to make circleci required?

**Pull request merged**
