### PR TITLE
fix: DAH-2744 Uninitialized Unleash Constant in Rails

### PR DESCRIPTION
**Pull request by jimlin-sfgov**
## Description

Fix Unleash configuration in Rails, specifically for rake tasks and sidekiq jobs.

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-2744

### Version Control

- [x] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [x] if the code changes the UI, it matches the UI design exactly

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [x] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Comment by tallulahkay** [comment]
@jimlin-sfgov The review instructions pass, but the Unleash flag still doesn't work in rails - there is not a hot reload, so if you toggle the flag while the environment is live, then the behavior based on the flag doesn't change.

re: [this ticket](https://sfgovdt.jira.com/browse/DAH-2667)

**Comment by jimlin-sfgov** [comment]
@tallulahkay 

> there is not a hot reloa

This is fixed now. I also updated the review instructions

**Comment by cade-exygy** [comment]
Testing criteria passes when running locally, but does not pass when running in the PR environment. I am not seeing any change in PR env Rails behavior when switching the GoogleCloudTranslate toggle.

**Comment by jimlin-sfgov** [comment]
Switching from a base constant to the `Rails.configuration` object as the means to store the Unleash client instance has solved the issues. This is the alternative way for storing the client according to the [official Unleash docs](https://github.com/Unleash/unleash-client-ruby?tab=readme-ov-file#3-sample-usage).

ready for review again @tallulahkay @cade-exygy

**Review by tallulahkay — APPROVED** [review]
WOOO! Thanks so much for figuring this out Jim! Rails 👑

**Pull request merged**
