### PR TITLE
DAH-2342: Connect Applications API to My Applications page

### PR DESCRIPTION
**Pull request by chadbrokaw**
[DAH-2342](https://sfgovdt.jira.com/browse/DAH-2342)

[DAH-2342]: https://sfgovdt.jira.com/browse/DAH-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jimlin-sfgov — COMMENTED** [review]
I believe the codeclimate issues are warranted, let me know if you need assistance fixing them.

**Comment by chadbrokaw** [comment]
> I believe the codeclimate issues are warranted, let me know if you need assistance fixing them.

Got it! In taking a look again I agree that the Codeclimate issues identified on my-applications are valid, however I'm not sure that they are warranted on the application-item page for the reason that the components being duplicated are mostly utility components (Modal and Button), with the core logic remaining in one place in the ListingDetailsLotterySearchForm component. What do you think? For the CodeClimate issues identified on application-item what would be your preferred way of fixing them?

**Comment by jimlin-sfgov** [comment]
> however I'm not sure that they are warranted on the application-item page

@chadbrokaw Agreed, that's why I had flagged them as invalid issues within codeclimate. The only remaining issue is the function `determineApplicationItemList` being too long, is there some way to simplify it?

**Comment by chadbrokaw** [comment]
> > however I'm not sure that they are warranted on the application-item page
> 
> @chadbrokaw Agreed, that's why I had flagged them as invalid issues within codeclimate. The only remaining issue is the function `determineApplicationItemList` being too long, is there some way to simplify it?

Thanks for flagging those as invalid! I see that error about it being too long. I did some work to optimize it, and I'm sure that I could simplify it 

> > however I'm not sure that they are warranted on the application-item page
> 
> @chadbrokaw Agreed, that's why I had flagged them as invalid issues within codeclimate. The only remaining issue is the function `determineApplicationItemList` being too long, is there some way to simplify it?

I went in and further simplified `determineApplicationItemList` so that it is below the line threshold (though personally it seems less readable now than before). Let me know if that is good!

**Comment by jimlin-sfgov** [comment]
> Let me know if that is good!

It is flawless

**Review by jimlin-sfgov — APPROVED** [review]

**Comment by chadbrokaw** [comment]
@jimlin-sfgov Would you mind looking over this one more time? We added some tests to ensure CodeClimate passed

**Review by jimlin-sfgov — APPROVED** [review]
lg

**Pull request merged**
