### PR TITLE
fix: DAH-2052 Remove log message about missing index method

### PR DESCRIPTION
**Pull request by jimlin-sfgov**
https://sfgovdt.jira.com/browse/DAH-2052

### CODE REVIEW

**Review by chadbrokaw — APPROVED** [review]
Thank you for taking care of this! 🎉

**Comment by alulabeshue-sfgov** [comment]
It also looks like this was [fixed](https://github.com/newrelic/newrelic-ruby-agent/issues/2048) in the newrelic ruby agent. We are currently using 9.0.0 according to the papertrail logs, if we update to 9.3.0 we may not need this empty function.

**Comment by jimlin-sfgov** [comment]
> if we update to 9.3.0 we may not need this empty function.

Good find, I'll create another infra ticket to specify the gem version for `newrelic_rpm` so we can update it to the latest version.

**Comment by jimlin-sfgov** [comment]
Closing this PR since the issue is not urgent, and the suggestion to update the newrelic gem instead is a better approach.

**Pull request closed without merging**
