### PR TITLE
Add COVID-19 update info [DAH-681]

### PR DESCRIPTION
**Pull request by software-project**
Resolves: [DAH-681](https://sfgovdt.jira.com/browse/DAH-681)

To fulfill the task `ALERT_MESSAGE` env var needs to be empty and `COVID_UPDATE` set to `true`

### CODE REVIEW

**Review by james-wills-sf — CHANGES_REQUESTED** [review]
@software-project it looks like the copy on the "Apply" button update should be this: "Paper applications are not currently being accepted due to COVID-19. All applications must be submitted online via the link above.”

**Comment by software-project** [comment]
@james-wills-sf translation is updated.

**Comment by james-wills-sf** [comment]
The code lgtm but I asked a follow up question on [the ticket](https://sfgovdt.jira.com/browse/DAH-681) about whether we also want to change the text for post-lottery listings, waiting for a response

**Review by james-wills-sf — APPROVED** [review]
@software-project just saw your latest jira comment, this lgtm.

Are you able to upload to Phrase? Not sure what permissions are required. If you can you should upload the new strings to phrase after this is merged (instructions in the readme)

**Review by james-wills-sf — COMMENTED** [review]
@software-project lgtm!

**Pull request merged**
