### PR TITLE
DAH-1770 Fix missing favicon in Safari

### PR DESCRIPTION
**Pull request by jimlin-sfgov**
https://sfgovdt.jira.com/browse/DAH-1770

### CODE REVIEW

**Comment by chadbrokaw** [comment]
Please let me know if I'm missing something, but I'm still not able to see the favicon in Safari. Running MacOS Ventura. Everything works correctly on Chrome, Firefox, and Arc.

I sent you a Slack message with a video (for some reason I can't upload it here)

**Comment by jimlin-sfgov** [comment]
> but I'm still not able to see the favicon in Safari

I'm am also not able to now, I'll need to revisit this PR, marking it as WIP for now

**Comment by jimlin-sfgov** [comment]
The latest changes should work now, although it is a bit of a bandaid solution. The core issue of `react-helmet-async` not working with Safari (and to a lesser extent Firefox) has not been resolved.

**Comment by chadbrokaw** [comment]
> The latest changes should work now, although it is a bit of a bandaid solution. The core issue of `react-helmet-async` not working with Safari (and to a lesser extent Firefox) has not been resolved.
> 
> A longer term solution would involve:
> 
> 1. checking if we even need `react-helmet-async` (there doesn't seem to be any dynamic context in our meta tags)
> 2. if we don't, then how to set up meta tags without `react-helmet-async`
>    
>    * we may need to update implementation of `ConfigContext` and `assetPaths`

Thank you for diving into this! That is frustrating about react-helmet-async. 

I tested it on safari and I'm still unable to see it? Not sure if it is something on my end; I restarted everything on Safari and cleared the cache

**Review by chadbrokaw — APPROVED** [review]
Looks great!

**Pull request merged**
